name: "Deploy-miner"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'v0.0.0'
        required: true
      platforms:
        description: 'amd64 (Dev) | amd64,arm64 (Prod)'
        required: true
        default: 'amd64'

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ github.event.inputs.platforms }}
          file: ./server/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pozk-miner:${{ github.event.inputs.version }}
          build-args: RELEASE_VERSION=${{ github.event.inputs.version }}
          ssh: default

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
